"""New migration message

Revision ID: 015b8225ef36
Revises: 2b1c1fe3e0e7
Create Date: 2025-03-06 07:05:53.999576

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '015b8225ef36'
down_revision = '2b1c1fe3e0e7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.add_column(sa.Column('email', sa.String(length=120), nullable=False))
        batch_op.alter_column('password_hash',
               existing_type=sa.VARCHAR(length=128),
               type_=sa.String(length=512),
               existing_nullable=False)
        batch_op.create_unique_constraint('uq_email', ['email'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='unique')
        batch_op.alter_column('password_hash',
               existing_type=sa.String(length=512),
               type_=sa.VARCHAR(length=128),
               existing_nullable=False)
        batch_op.drop_column('email')

    # ### end Alembic commands ###
