"""Added extra columns to Store model

Revision ID: 9890758b8bd9
Revises: f76e1da67dfd
Create Date: 2025-03-06 23:50:40.865866

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '9890758b8bd9'
down_revision = 'f76e1da67dfd'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.add_column(sa.Column('store_type', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('stores', schema=None) as batch_op:
        batch_op.drop_column('store_type')

    # ### end Alembic commands ###
